version: 2
updates:
  - package-ecosystem: npm
    directory: /
    target-branch: dev
    schedule:
      interval: weekly
    groups:
      dependances:
        patterns: ["*"]
        update-types: [minor, patch]
    labels: [chore]

  - package-ecosystem: github-actions
    directory: /
    target-branch: dev
    schedule:
      interval: weekly
    labels: [chore]

  - package-ecosystem: docker
    directory: /
    target-branch: dev
    schedule:
      interval: weekly
    labels: [chore]
